[package]
name = "nvda-rust-uia-standalone"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies.windows]
git = "https://github.com/microsoft/windows-rs.git"
rev = "6195af4858f13bb3714e901d9bda6bc38abcfbf7"
default-features = true
features = [
    "UI_UIAutomation",
    "combaseapi",
    "objbase",
    "uiautomationclient",
    "uiautomationcore",
    "UI_UIAutomation_Core",
    "audioclient",
    "Devices_HumanInterfaceDevice",
    "winuser",
    "windef",
]

[dependencies.windows-core]
git = "https://github.com/microsoft/windows-rs.git"
rev = "6195af4858f13bb3714e901d9bda6bc38abcfbf7"
default-features = true

[profile.release]
lto = "thin"
strip = "debuginfo"
